config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'file/index'
  get 'survey/index'
  #get 'questions/index'
  get 'questions/thankyou' => 'questions#thankyou'

  get 'file/index' => 'file#index'
  resources :file

  resources :questions
  #get 'survey/index' => 'survey#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'questions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord

  validates :firstName, :lastName, :phoneNumber, :presence => true
  validates :phoneNumber, :length => {:minimum => 12}

  def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |product|
          csv << product.attributes.values_at(*column_names)
        end
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/excelcvs_controller.rb
class ExcelcvsController < ApplicationController
end

app/controllers/file_controller.rb
class FileController < ApplicationController
  def index
    @patients = Question.all
    respond_to do |format|
      format.html
      format.csv {send_data @patients.to_csv}
      format.xls
    end
  end

  def show

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, only: [:index]

  def index
    @patients = Question.all
    respond_to do |format|
      format.html
      format.csv {send_data @patients.to_csv}
      format.xls
    end
  end

  def new

  end

  def show

    #@patient = Question.find(params[:id])


  end

  def thankyou

  end


  def create


    @patient = Question.new(questions_params)
    @patient.dateSubmitted = DateTime.parse(Time.now.to_s).strftime("%m/%d/%Y %R")
    @answers = @patient.answers
    @patient.save

    puts("BELOW ERRORS........")
    @patient.errors.full_messages.each do |msg|
      puts(msg)
    end

    render 'questions/thankyou'

  end

  private def questions_params
    params.require(:questions).permit(:id, :firstName, :lastName, :phoneNumber, :answers);
  end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
  def index

  end

  def new

  end

  def create
    render js: "alert:('wtf');"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excelcvs_helper.rb
module ExcelcvsHelper
end

app/helpers/file_helper.rb
module FileHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/file/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">First Name</Data></Cell>
        <Cell><Data ss:Type="String">Last Name</Data></Cell>
        <Cell><Data ss:Type="String">Phone Number</Data></Cell>
        <Cell><Data ss:Type="String">Date Submitted</Data></Cell>
        <Cell><Data ss:Type="String">Date Submitted</Data></Cell>
      </Row>
    <% @patients.each do |patient| %>
      <Row>
        <Cell><Data ss:Type="String"><%= patient.firstName %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.lastName %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.phoneNumber %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.dateSubmitted %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.answers %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Survey</title>
    <%= favicon_link_tag 'favicon.ico' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">

    <link href="https://fonts.googleapis.com/css?family=Overpass&display=swap" rel="stylesheet">

  </head>
  <body>
    <br>
    <div class="container">
        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% end %>
        <table class="table table-striped table-bordered table-dark" id="patientTable" style="width:100%">
          <thead>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Date</th>
            <th scope="col">Answers</th>
          </thead>
          <tbody>
            <% @patients.each do |p| %>
            <tr>
              <td> <%= p.firstName %> </td>
              <td> <%= p.lastName %> </td>
              <td> <%= p.phoneNumber %> </td>
              <td> <%= p.dateSubmitted %> </td>
              <td> <%= p.answers %> </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="btn btn-dark"><%= link_to "Download", file_index_path(format: 'csv') %></div>
    </div>




    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js">

    </script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js">
    </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'survey' %>
  </body>
</html?

app/views/questions/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Survey</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

    <%= stylesheet_link_tag 'survey' %>
    <link href="https://fonts.googleapis.com/css?family=Overpass&display=swap" rel="stylesheet">




  </head>
  <body>
    <!--<input type="checkbox"/> -->
    <div class="content">
      <div id="grid">
        <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
      </div>
      <div class="heading">
        <div class="logo"> <%=  image_tag("DHRHSLogo", class:'logo logo-img') %> </div>
        <div class="title"> <h1>| Patient Survey</h1> </div>
      </div>
      <div class="survey">
        <div class="question">
          <%  puts("QUESTIONS") %>
          <%  puts(@questions) %>
            <h2></h2>

        </div>
        <div class="answers">
          <div id="happy"> <%=  image_tag("happy", class:'answers-img') %> </div>
          <div id="neutral"> <%=  image_tag("neutral", class:'answers-img') %> </div>
          <div id="unhappy"> <%=  image_tag("unhappy2", class:'answers-img') %> </div>
        </div>

        <div class="patient-info">

          <%= form_for :questions, url: questions_path, html:{class:"patientForm"} do |f| %>

            <div class="form-group">
              <%= f.label :firstName, 'First Name', for:'validation'%>
              <%= f.text_field :firstName, class:'form-control', id:'firstName', required: true%>

            </div>
            <div class="form-group">
              <%= f.label :lastName, 'Last Name'%>
              <%= f.text_field :lastName, class:'form-control', id:'lastName', required: true%>
            </div>
            <div class="form-group">
              <%= f.label :phoneNumber, 'Phone Number'%>
              <%= f.text_field :phoneNumber, class: 'form-control', id:'phoneNumber', required: true%>
            </div>
            <div class="form-group" style="display:none">
              <%= f.label :answers, 'Answers'%>
              <%= f.text_field :answers, class: 'form-control', id: "answers"%>
            </div>
            <%= f.submit 'Submit', class:'btn btn-primary' %>
          <% end %>


        </div>
      </div>

      <footer> <hr><p>DHR Health</p> </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js"></script>

    <script>
      bootstrapValidate('#firstName', 'required:Please fill out this field!');
      bootstrapValidate('#lastName', 'required:Please fill out this field!');
      bootstrapValidate('#phoneNumber', 'regex:[0-9][0-9[0-9]\-[0-9][0-9][0-9]\-[0-9][0-9][0-9][0-9]:Format must be XXX-XXX-XXXX');
      bootstrapValidate('#phoneNumber', 'min:12:Please enter your 10-digit phone number');
      bootstrapValidate('#phoneNumber', 'max:12:You entered too many characters');
    </script>

    <%= javascript_pack_tag 'survey' %>
  </body>
</html>

app/views/questions/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Survey</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'survey' %>
    <link href="https://fonts.googleapis.com/css?family=Overpass&display=swap" rel="stylesheet">

  </head>
  <body>
    <!--<input type="checkbox"/> -->
    <div class="content">
      <div id="grid">
        <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
      </div>
      <div class="heading">
        <div class="logo"> <%=  image_tag("DHRHSLogo", class:'logo logo-img') %> </div>
        <div class="title"> <h1>| Patient Survey</h1> </div>
      </div>
      <div class="survey">

        <div class="thankyou">

          <h2>Thank you for providing your feedback</h2>

        </div>


      </div>

      <footer> <hr><p>DHR Health</p> </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'survey' %>
  </body>
</html>

app/views/questions/thankyou.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Survey</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'survey' %>
    <link href="https://fonts.googleapis.com/css?family=Overpass&display=swap" rel="stylesheet">

  </head>
  <body>
    <!--<input type="checkbox"/> -->
    <div class="content">
      <div id="grid">
        <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
      </div>
      <div class="heading">
        <div class="logo"> <%=  image_tag("DHRHSLogo", class:'logo logo-img') %> </div>
        <div class="title"> <h1>| Patient Survey</h1> </div>
      </div>
      <div class="survey">

        <div class="thankyou">
          <% if  @patient.errors.any?%>
          <% @patient.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <% end %>
          <div class="patient-info-errors">
            <%= form_for :questions, url: questions_path, html:{class:"patientForm"} do |f| %>

              <div class="form-group">
                <%= f.label :firstName, 'First Name', for:'validation'%>
                <%= f.text_field :firstName, class:'form-control', id:'firstName', required: true%>

              </div>
              <div class="form-group">
                <%= f.label :lastName, 'Last Name'%>
                <%= f.text_field :lastName, class:'form-control', id:'lastName', required: true%>
              </div>
              <div class="form-group">
                <%= f.label :phoneNumber, 'Phone Number'%>
                <%= f.text_field :phoneNumber, class: 'form-control', id:'phoneNumber', required: true%>
              </div>
              <div class="form-group" style="display:none">
                <%= f.label :answers, 'Answers'%>
                <% puts("HERE") %>
                <% puts(@answers) %>
                <%= f.text_field :answers, class: 'form-control', value: @answers, id: "answers"%>

              </div>
              <%= f.submit 'Submit', class:'btn btn-primary' %>

            <% end %>
          </div>
          <% else %>
          <h2>Thank you for providing your feedback</h2>
          <% end %>

        </div>


      </div>

      <footer> <hr><p>DHR Health</p> </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js"></script>
    <script>
      bootstrapValidate('#firstName', 'required:Please fill out this field!');
      bootstrapValidate('#lastName', 'required:Please fill out this field!');
      bootstrapValidate('#phoneNumber', 'regex:[0-9][0-9[0-9]\-[0-9][0-9][0-9]\-[0-9][0-9][0-9][0-9]:Format must be XXX-XXX-XXXX');
      bootstrapValidate('#phoneNumber', 'min:12:Please enter your 10-digit phone number');
      bootstrapValidate('#phoneNumber', 'max:12:You entered too many characters');
    </script>
    <%= javascript_pack_tag 'survey' %>
  </body>
</html>

app/views/survey/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Survey</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'survey' %>
    <link href="https://fonts.googleapis.com/css?family=Overpass&display=swap" rel="stylesheet">

  </head>
  <body>
    <!--<input type="checkbox"/> -->
    <div class="content">
      <div id="grid">
        <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
      </div>
      <div class="heading">
        <div class="logo"> <%=  image_tag("DHRHSLogo", class:'logo logo-img') %> </div>
        <div class="title"> <h1>| Patient Survey</h1> </div>
      </div>
      <div class="survey">
        <div class="question">
          <h2></h2>
        </div>
        <div class="answers">

          <div id="unhappy"> <%=  image_tag("unhappy2", class:'answers-img') %> </div>
          <div id="neutral"> <%=  image_tag("neutral", class:'answers-img') %> </div>
          <div id="happy"> <%=  image_tag("happy", class:'answers-img') %> </div>

        </div>

        <div class="patient-info">

          <%= form_for :survey, url: survey_index_path do |f| %>
            <div class="form-group">
              <%= f.label :firstName, 'First Name'%>
              <%= f.text_field :firstName, class:'form-control'%>
            </div>
            <div class="form-group">
              <%= f.label :lastName, 'Last Name'%>
              <%= f.text_field :lastName, class:'form-control'%>
            </div>
            <div class="form-group">
              <%= f.label :phoneNumber, 'Phone Number'%>
              <%= f.text_field :phoneNumber, class: 'form-control'%>
            </div>
            <%= f.submit 'Submit', class:'btn btn-primary' %>
          <% end %>
          <!-- <form>
            <div class="form-group">
              <label for="first-name">First Name</label>
              <input type="text" name="fistName" class="form-control" id="first-name" placeholder="Fist Name">
            </div>
            <div class="form-group">
              <label for="last-name">Last Name</label>
              <input type="text" name="lastName" class="form-control" id="last-name" placeholder="Last Name">
            </div>
            <div class="form-group">
              <label for="phone-number">Phone Number</label>
              <input type="text" name="phoneNumber" class="form-control" id="phone-number" placeholder="Phone Number">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form> -->

        </div>
      </div>

      <footer> <hr><p>DHR Health</p><hr> </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'survey' %>
  </body>
</html>